Lambda dev esrf master new sdk
soleil-ica/Lima-camera-lambda pull request #2
Opened 2022-04-27 12:34 UTC by SixtineHostache

Modification of LAMBDA sdk after :
- Updating the lib xsp to 2.0.3 
- Adding the libVersion attribute
- Adding the "hasFeature" function

2022-04-27 12:35 UTC, SixtineHostache commented
ok

2022-05-02 13:48 UTC, soleil-ica requested changes

2022-05-02 13:48 UTC, soleil-ica commented on include/LambdaCamera.h
> +	string getLibVersion(std::string &libVersion);
std::string getLibVersion

2022-05-02 13:48 UTC, soleil-ica commented on sdk/include/libxsp_old.h
> +//
Fichier à supprimer

2022-05-02 13:48 UTC, soleil-ica commented on src/LambdaCamera.cpp
> +string Camera::getLibVersion(std::string &libVersion)
soit pas parametres, soit pas retour, mais pas les 2.
plutot par parametres pour etre cohérent avec le reste

2022-05-02 13:48 UTC, soleil-ica commented on src/LambdaCamera.cpp
> +	stringstream ss;
la fonction retourne directement un std::string, donc pas besoin de passer par stringstream il me semble

2022-05-02 13:48 UTC, soleil-ica commented on src/LambdaCamera.cpp
> +	std::cout << "has Feature entering "<< std::endl;
enlever le cout
(le DEB_MEMEBER_FUNCT() fait deja cela)

2022-05-02 16:04 UTC, soleil-ica commented
attention, il faudrait que le PR pointe vers master au lieu de esrf-master-new-sdk

2022-05-11 15:54 UTC, soleil-ica approved these changes

2022-05-11 15:58 UTC, merged