[ICATHALES-460] Add  decoding parameters features
soleil-ica/Lima-camera-lambda pull request #4
Opened 2023-04-19 15:13 UTC by sbahji

CountrateCorrection + SaturationFlag + SaturationThreshold Features

2023-04-19 16:06 UTC, ghost requested changes

2023-04-19 16:06 UTC, soleil-ica commented on pom_64_el7.xml
> +    <version>2.0.2-SNAPSHAT</version>
snapshOt

2023-04-19 16:06 UTC, soleil-ica commented on src/LambdaCamera.cpp
> +//! get the value of if flagging of pixel saturation is enabled
pas clair

2023-04-19 16:06 UTC, soleil-ica commented on src/LambdaCamera.cpp
> +    //module_nr: module number
quid si plusieurs modules? et d'ailleurs qu'est ce qu'un module?

2023-04-20 07:24 UTC, sbahji commented on pom_64_el7.xml
> +    <version>2.0.2-SNAPSHAT</version>
Ok

2023-04-21 08:59 UTC, ghost approved these changes

2023-04-21 09:00 UTC, merged