[ICATHALES-474] Update index.rst and tango.rst files
soleil-ica/Lima-camera-lambda pull request #5
Opened 2023-04-19 18:51 UTC by sbahji

Update index.rst and tango.rst files

2023-04-20 07:43 UTC, soleil-ica requested changes

2023-04-20 07:43 UTC, soleil-ica commented on doc/tango.rst
Ce n'est malheureusement pas ce fichier qu'il faut modifier: celui la correspond au device Tango Python de l'esrf.
le notre, celui qui correspond au device Tango / C++ se trouve ici : application/tango/cpp/doc/Lambda/lambda.rst

2023-04-20 11:01 UTC, sbahji commented on doc/tango.rst
Ok je remet la version précédente

2023-04-21 08:26 UTC, soleil-ica approved these changes

2023-04-21 08:28 UTC, merged